use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

const PROVISION_FINGERPRINT_SALT: &[u8] = b"agbranch-base-fingerprint-v1\0";
const ASSET_BUNDLE_FINGERPRINT_SALT: &[u8] = b"agbranch-asset-bundle-fingerprint-v1\0";

fn main() {
    let root = std::env::var_os("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .expect("CARGO_MANIFEST_DIR should be set by Cargo");

    // Emit directory-level rerun directives once. Per-file directives come
    // from the input-discovery helpers below.
    println!("cargo:rerun-if-changed=lima/safe-sync-macos.yaml");
    println!("cargo:rerun-if-changed=lima/safe-sync-linux.yaml");
    println!("cargo:rerun-if-changed=lima/provision");
    println!("cargo:rerun-if-changed=lima/guest");

    let provision_inputs =
        provision_fingerprint_inputs(&root).expect("provision fingerprint inputs");
    let provision_fingerprint = compute_fingerprint(provision_inputs, PROVISION_FINGERPRINT_SALT)
        .expect("provision fingerprint");
    println!("cargo:rustc-env=AGBRANCH_PROVISION_FINGERPRINT={provision_fingerprint}");

    let bundle_inputs = asset_bundle_fingerprint_inputs(&root).expect("asset bundle inputs");
    let bundle_paths: Vec<String> = bundle_inputs
        .iter()
        .map(|input| input.path.clone())
        .collect();
    let bundle_fingerprint = compute_fingerprint(bundle_inputs, ASSET_BUNDLE_FINGERPRINT_SALT)
        .expect("asset bundle fingerprint");
    println!("cargo:rustc-env=AGBRANCH_ASSET_BUNDLE_FINGERPRINT={bundle_fingerprint}");

    write_embedded_asset_manifest(&root, &bundle_paths).expect("write embedded asset manifest");
}

fn write_embedded_asset_manifest(root: &Path, bundle_paths: &[String]) -> Result<(), String> {
    let out_dir = std::env::var_os("OUT_DIR")
        .map(PathBuf::from)
        .ok_or_else(|| "OUT_DIR should be set by Cargo".to_owned())?;
    let manifest_path = out_dir.join("lima_assets.rs");

    // Paths are already sorted bytewise because `load_inputs` sorted them
    // before hashing. The generated manifest preserves that order so the
    // runtime sort-invariant test is satisfied.
    let mut sorted_paths: Vec<&str> = bundle_paths.iter().map(String::as_str).collect();
    sorted_paths.sort_by(|left, right| left.as_bytes().cmp(right.as_bytes()));

    let mut source = String::new();
    source.push_str(
        "// Generated by build.rs. Do not edit.\n\
pub const EMBEDDED_LIMA_ASSETS: &[EmbeddedAsset] = &[\n",
    );
    for path in &sorted_paths {
        let relative_to_lima = path
            .strip_prefix("lima/")
            .ok_or_else(|| format!("asset path `{path}` missing lima/ prefix"))?;
        source.push_str("    EmbeddedAsset {\n");
        source.push_str(&format!(
            "        relative_path: {},\n",
            escape_rust_string(relative_to_lima)
        ));
        source.push_str(&format!(
            "        bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\")),\n",
            path.replace('\\', "\\\\").replace('"', "\\\"")
        ));
        source.push_str("    },\n");
    }
    source.push_str("];\n");

    // Best-effort check that every referenced path exists at generation
    // time. Missing files would fail include_bytes! later with a less
    // helpful error, so fail early here.
    for path in &sorted_paths {
        let full = root.join(path);
        if !full.is_file() {
            return Err(format!(
                "asset `{}` not found at `{}`",
                path,
                full.display()
            ));
        }
    }

    std::fs::write(&manifest_path, source)
        .map_err(|err| format!("failed to write `{}`: {err}", manifest_path.display()))?;
    Ok(())
}

fn escape_rust_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_ascii_control() => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[derive(Debug, Clone)]
struct FingerprintInput {
    path: String,
    bytes: Vec<u8>,
}

fn provision_fingerprint_inputs(root: &Path) -> Result<Vec<FingerprintInput>, String> {
    let mut paths = vec![
        PathBuf::from("lima/safe-sync-macos.yaml"),
        PathBuf::from("lima/safe-sync-linux.yaml"),
    ];
    for path in discover_non_recursive_scripts(root, "provision")? {
        println!("cargo:rerun-if-changed={}", to_posix(&path));
        paths.push(path);
    }
    load_inputs(root, paths)
}

fn asset_bundle_fingerprint_inputs(root: &Path) -> Result<Vec<FingerprintInput>, String> {
    let mut paths = vec![
        PathBuf::from("lima/safe-sync-macos.yaml"),
        PathBuf::from("lima/safe-sync-linux.yaml"),
    ];
    for path in discover_non_recursive_scripts(root, "provision")? {
        paths.push(path);
    }
    for path in discover_non_recursive_scripts(root, "guest")? {
        println!("cargo:rerun-if-changed={}", to_posix(&path));
        paths.push(path);
    }
    load_inputs(root, paths)
}

fn load_inputs(root: &Path, mut paths: Vec<PathBuf>) -> Result<Vec<FingerprintInput>, String> {
    paths.sort_by(|left, right| to_posix(left).as_bytes().cmp(to_posix(right).as_bytes()));
    paths
        .into_iter()
        .map(|path| {
            let full_path = root.join(&path);
            let bytes = std::fs::read(&full_path)
                .map_err(|err| format!("failed to read `{}`: {err}", full_path.display()))?;
            Ok(FingerprintInput {
                path: to_posix(&path),
                bytes,
            })
        })
        .collect()
}

fn discover_non_recursive_scripts(root: &Path, subdir: &str) -> Result<Vec<PathBuf>, String> {
    let dir = root.join("lima").join(subdir);
    let entries = std::fs::read_dir(&dir)
        .map_err(|err| format!("failed to read `{}`: {err}", dir.display()))?;
    let mut scripts = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|err| err.to_string())?;
        let file_type = entry.file_type().map_err(|err| err.to_string())?;
        if !file_type.is_file() {
            continue;
        }
        let path = entry.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("sh") {
            continue;
        }
        scripts.push(PathBuf::from("lima").join(subdir).join(entry.file_name()));
    }
    scripts.sort();
    Ok(scripts)
}

fn compute_fingerprint<I>(inputs: I, salt: &[u8]) -> Result<String, String>
where
    I: IntoIterator<Item = FingerprintInput>,
{
    let mut inputs = inputs.into_iter().collect::<Vec<_>>();
    inputs.sort_by(|left, right| left.path.as_bytes().cmp(right.path.as_bytes()));

    let mut hasher = Sha256::new();
    hasher.update(salt);
    for input in inputs {
        if input.path.is_empty() {
            return Err("fingerprint input path must not be empty".to_owned());
        }
        let path_len = input.path.len().to_string();
        let content_len = input.bytes.len().to_string();
        hasher.update(path_len.as_bytes());
        hasher.update(b"\0");
        hasher.update(input.path.as_bytes());
        hasher.update(b"\0");
        hasher.update(content_len.as_bytes());
        hasher.update(b"\0");
        hasher.update(&input.bytes);
        hasher.update(b"\0");
    }

    Ok(format!("sha256:{}", hex::encode(hasher.finalize())))
}

fn to_posix(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}
